# Generated by Django 3.2.6 on 2022-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20220611_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='file',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='work',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
