# Generated by Django 3.2.6 on 2022-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20220611_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
    ]
