# Generated by Django 3.2.6 on 2022-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20220611_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dath_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dath_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dath_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
