# Generated by Django 3.2.6 on 2022-06-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_alter_file_acceptance_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='acceptance_letter',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
