# Generated by Django 3.2.6 on 2022-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_alter_file_acceptance_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('e_mail', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
