# Generated by Django 3.2.6 on 2022-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_work_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('rejected', 'Rejected'), ('solved', 'Solved')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='new', max_length=32),
        ),
    ]
